### PR TITLE
Bundle Lutris with the Addon

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by strycore** [comment]
Hmm… wouldn't you want to use git submodules for that? This pull request duplicates the whole client repository, It's going to be hard to keep it up to date with the original repo.

**Comment by RobLoach** [comment]
I agree. Main concern here was distribution. Not quite sure if [SuperRepo will bundle Lutris](https://superrepo.org/kodi/addon/script.lutris/) with the submodules in place.

**Comment by strycore** [comment]
Well, that's the thing: you don't distribute git repos with something other than git. Usually, source repos will have a Makefile rule such as "make dist" that will build a tar.gz ready for distribution.

This is why some autotools projects will have a configure script bundled with the source but won't have it in the git repo as it will have to be generated by autogen.sh. 

In the case of Lutris, some things are not needed for distribution: the debian folder, the RPM spec file an probably some other things. Those would be the files you wouldn't include in a build step for package distribution. I don't know the exact process of submitting packages to SuperRepo but there as to be a better way than bundling a snapshot of a specific commit.

**Comment by RobLoach** [comment]
I don't like this approach. The Lutris debian package comes with some dependencies that are good to bring in. I'll keep to instructing the user to install Lutris in the usual methods.

**Pull request closed without merging**
